// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdTW-y6QhvjPsD-u12k9lq6ipjPQiiwyQ',
    appId: '1:517695311427:web:59bb6917b1352258bd0ef6',
    messagingSenderId: '517695311427',
    projectId: 'agri-track-d349a',
    authDomain: 'agri-track-d349a.firebaseapp.com',
    storageBucket: 'agri-track-d349a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOdYDRTalLP-PGIn13bBi_Z437Nf9a2dA',
    appId: '1:517695311427:android:25521afbe4d923debd0ef6',
    messagingSenderId: '517695311427',
    projectId: 'agri-track-d349a',
    storageBucket: 'agri-track-d349a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtmBFZJlv4adPT8kNAaT5-DvisuT9bkbE',
    appId: '1:517695311427:ios:a048f72f6f354cb8bd0ef6',
    messagingSenderId: '517695311427',
    projectId: 'agri-track-d349a',
    storageBucket: 'agri-track-d349a.firebasestorage.app',
    iosBundleId: 'com.example.bovitrack',
  );
}
